"""Zeros of L(s, chi_{-4}) on the critical line, by sign changes of the completed function.

chi_{-4} is odd, q = 4, root number 1 (checked: Lambda(1/2+it) is real to 1e-22), so
    Z(t) := Re[ e^{i theta(t)} L(1/2+it, chi_{-4}) ],
    e^{i theta(t)} := phase of (4/pi)^{it/2} Gamma((3/2+it)/2),
is real. Sign-changing zeros are located by a scan of step H followed by bisection
to TOL. The scan can miss close pairs or even-multiplicity zeros. Window counts
and optional comparisons with independently generated lists are numerical checks,
not completeness certificates.

Usage:  python compute/chi4_zeros.py --tmax 3000 [--validate]
Output: data/chi4_zeros.txt  (one ordinate per line, appended as found; header lines start with #)
        data/chi4_zeros.log  (progress and the per-window count check)
"""

import argparse, sys, time
from pathlib import Path
import mpmath as mp
from validate_zeros import read, unmatched

ROOT = Path(__file__).resolve().parents[1]

mp.mp.dps = 20
CHI = [0, 1, 0, -1]
H = 0.05            # scan step; zero density at T=1e4 is ~1.4 per unit
TOL = mp.mpf('1e-12')


def Z(t):
    t = mp.mpf(t)
    s = mp.mpc(0.5, t)
    g = mp.gamma((mp.mpf(3) / 2 + 1j * t) / 2)
    phase = mp.power(4 / mp.pi, 1j * t / 2) * g / abs(g)
    return (phase * mp.dirichlet(s, CHI)).real


def theta(t):
    """theta(t) = (t/2) log(4/pi) + Im log Gamma((3/2+it)/2); N(t) ~ theta(t)/pi + const."""
    t = mp.mpf(t)
    return (t / 2) * mp.log(4 / mp.pi) + mp.loggamma((mp.mpf(3) / 2 + 1j * t) / 2).imag


def overlap_check(mine, reference):
    ref = read(reference)
    if mine[-1] < ref[0] or ref[-1] < mine[0]:
        return False, 'INVALID: no overlapping reference ordinates'
    lo = max(mine[0], ref[0]) - 1e-6
    hi = min(mine[-1], ref[-1]) + 1e-6
    a = [g for g in mine if lo <= g <= hi]
    b = [g for g in ref if lo <= g <= hi]
    missing_a, missing_b = unmatched(a, b), unmatched(b, a)
    good = not missing_a and not missing_b
    return good, '%s: overlap with %s: %d / %d ordinates, unmatched %d / %d' % (
        'VALID' if good else 'INVALID', reference, len(a), len(b), len(missing_a), len(missing_b))


def bisect(a, b, fa, fb):
    for _ in range(80):
        m = (a + b) / 2
        fm = Z(m)
        if fm == 0:
            return m
        if (fm > 0) == (fa > 0):
            a, fa = m, fm
        else:
            b, fb = m, fm
        if b - a < TOL:
            break
    return (a + b) / 2


def find_zeros(t0, t1, log):
    zeros = []
    t = mp.mpf(t0)
    fa = Z(t)
    if fa == 0:
        zeros.append(t)
    while t < t1:
        tn = min(t + H, mp.mpf(t1))
        fb = Z(tn)
        if fb == 0:
            zeros.append(tn)
        elif (fb > 0) != (fa > 0):
            zeros.append(bisect(t, tn, fa, fb))
        t, fa = tn, fb
    return zeros


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--tmax', type=float, default=3000)
    ap.add_argument('--validate', action='store_true')
    ap.add_argument('--reference', type=Path, default=ROOT / 'data/chi4_zeros_pari10000_clean.txt',
                    help='Overlap comparison used by --validate')
    ap.add_argument('--tmin', type=float, default=0.0)
    ap.add_argument('--out', default='data/chi4_zeros.txt')
    args = ap.parse_args()
    if not (mp.isfinite(args.tmin) and mp.isfinite(args.tmax) and 0 <= args.tmin < args.tmax):
        ap.error('require finite 0 <= tmin < tmax')
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)

    out = open(args.out, 'w', encoding='utf-8')
    log = open(args.out.rsplit('.',1)[0] + '.log', 'w', encoding='utf-8')
    out.write('# ordinates gamma>0 of zeros of L(s,chi_{-4}) on Re s=1/2, mpmath dps=%d, scan H=%s, bisect TOL=%s\n'
              % (mp.mp.dps, H, TOL))
    out.write('# generated by compute/chi4_zeros.py --tmax %g\n' % args.tmax)

    t_start = time.time()
    total = 0
    win = 100.0
    lo = args.tmin
    # constant in N(T) ~ theta(T)/pi + c: calibrate on the first window
    c_cal = None
    while lo < args.tmax:
        hi = min(lo + win, args.tmax)
        zs = find_zeros(lo, hi, log)
        if lo > args.tmin and zs and zs[0] == mp.mpf(lo):
            zs = zs[1:]  # A zero on a shared window boundary was already emitted.
        for z in zs:
            out.write(mp.nstr(z, 15) + '\n')
        out.flush()
        total += len(zs)
        expected = theta(hi) / mp.pi
        if c_cal is None:
            c_cal = total - expected
        dev = total - expected - c_cal
        msg = 't in [%7.1f,%7.1f]: %4d zeros, total %5d, theta/pi+c = %8.2f, dev %+5.2f, %.0fs' % (
            lo, hi, len(zs), total, float(expected + c_cal), float(dev), time.time() - t_start)
        log.write(msg + '\n'); log.flush()
        print(msg, flush=True)
        if abs(dev) > 1.5:
            log.write('   WARNING: count deviates from theta/pi by more than 1.5 -- possible missed pair\n'); log.flush()
        lo = hi
    out.close()

    if args.validate:
        try:
            mine = read(Path(args.out))
            good, msg = overlap_check(mine, args.reference)
        except (ValueError, OSError) as exc:
            good, msg = False, str(exc)
        log.write(msg + '\n'); print(msg, flush=True)
        if not good:
            log.close()
            raise SystemExit(1)
    log.write('done: %d zeros, %.0fs\n' % (total, time.time() - t_start)); log.close()


if __name__ == '__main__':
    main()
